services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: fpm
    volumes:
      - ./app:/var/www/html/app
      - ./public:/var/www/html/public
      - vendor:/var/www/html/vendor
      - ./public/dist:/var/www/html/public/dist
    env_file:
      - .env
    networks:
      - app-network

  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: web
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - app
    networks:
      - app-network

  db:
    image: postgres:13-alpine
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

volumes:
  db_data:
  vendor:

networks:
  app-network:
    driver: bridge